from django.contrib import admin
from cloudmeb.why_cloudmeb_txts.models import Why_cloudmeb_txt
from django.utils.translation import ugettext_lazy as _

class Why_cloudmeb_txtAdmin(admin.ModelAdmin):
    fileds = ('why_cloudmeb_txt_name', 'why_cloudmeb_txt_header_title_en', 'why_cloudmeb_txt_header_title_fr', 'why_cloudmeb_txt_header_subtitle_en', 'why_cloudmeb_txt_header_subtitle_fr', 'why_cloudmeb_txt_introduce_title_en', 'why_cloudmeb_txt_introduce_title_fr', 'why_cloudmeb_txt_introduce_text_en', 'why_cloudmeb_txt_introduce_text_fr', 'why_cloudmeb_txt_why_introduce_title_en', 'why_cloudmeb_txt_why_introduce_title_fr', 'why_cloudmeb_txt_why_introduce_text_en', 'why_cloudmeb_txt_why_introduce_text_fr', 'why_cloudmeb_txt_whytab_title_en', 'why_cloudmeb_txt_whytab_title_fr', 'why_cloudmeb_txt_whytab_subtitle_en', 'why_cloudmeb_txt_whytab_subtitle_fr', 'why_cloudmeb_txt_cta_text_en', 'why_cloudmeb_txt_cta_text_fr', 'why_cloudmeb_txt_logo_slider_title_en', 'why_cloudmeb_txt_logo_slider_title_fr', 'why_cloudmeb_txt_experience_title_en', 'why_cloudmeb_txt_experience_title_fr', 'why_cloudmeb_txt_testimonial_title_en', 'why_cloudmeb_txt_testimonial_title_fr',)
    list_display = ('why_cloudmeb_txt_name', 'why_cloudmeb_txt_header_title_en', 'why_cloudmeb_txt_header_title_fr', 'why_cloudmeb_txt_header_subtitle_en', 'why_cloudmeb_txt_header_subtitle_fr', 'why_cloudmeb_txt_introduce_title_en', 'why_cloudmeb_txt_introduce_title_fr', 'why_cloudmeb_txt_introduce_text_en', 'why_cloudmeb_txt_introduce_text_fr', 'why_cloudmeb_txt_why_introduce_title_en', 'why_cloudmeb_txt_why_introduce_title_fr', 'why_cloudmeb_txt_why_introduce_text_en', 'why_cloudmeb_txt_why_introduce_text_fr', 'why_cloudmeb_txt_whytab_title_en', 'why_cloudmeb_txt_whytab_title_fr', 'why_cloudmeb_txt_whytab_subtitle_en', 'why_cloudmeb_txt_whytab_subtitle_fr', 'why_cloudmeb_txt_cta_text_en', 'why_cloudmeb_txt_cta_text_fr', 'why_cloudmeb_txt_logo_slider_title_en', 'why_cloudmeb_txt_logo_slider_title_fr', 'why_cloudmeb_txt_experience_title_en', 'why_cloudmeb_txt_experience_title_fr', 'why_cloudmeb_txt_testimonial_title_en', 'why_cloudmeb_txt_testimonial_title_fr',)

admin.site.register(Why_cloudmeb_txt, Why_cloudmeb_txtAdmin)  
